import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const Home: NextPage = () => {
  const [endpoint, setEndpoint] = useState<string>("");
  const [code, setCode] = useState<string>("");
  const [response, setResponse] = useState<string>("no response");
  const handleSubmit = () => {
    const enc = encodeURIComponent(code);
    console.log(enc);
    if (endpoint === "") return;
    fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ data: code }),
    })
      .then((res) => res.json())
      .then((data) => setResponse(JSON.stringify(data)))
      .catch((e) => setResponse((e as Error).message));
  };
  return (
    <>
      <Head>
        <title>Code as a Service</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen w-full flex-col items-center gap-2 p-4">
        <input
          className="w-full"
          placeholder="type url"
          value={endpoint}
          onChange={(e) => setEndpoint(e.target.value)}
        />
        <div className="grid h-full w-full flex-1 grid-cols-2 gap-2">
          <div>
            <textarea
              className="h-1/2 w-full"
              value={code}
              onChange={(e) => setCode(e.target.value)}
            />
            <button onClick={handleSubmit}>Send</button>
          </div>
          <div className="w-full">{response}</div>
        </div>
      </main>
    </>
  );
};

export default Home;
