import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const Home: NextPage = () => {
  const [endpoint, setEndpoint] = useState<string>("");
  const [code, setCode] = useState<string>("");
  const [response, setResponse] = useState<string | null>(null);
  const handleSubmit = () => {
    const enc = encodeURIComponent(code);
    console.log(enc);
    if (endpoint === "") return;
    try {
      fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ data: code }),
      })
        .then((res) => res.json())
        .then((data) => setResponse(JSON.stringify(data)));
    } catch (e) {
      setResponse((e as Error).message);
    }
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center gap-2 p-4">
        <input
          placeholder="type url"
          value={endpoint}
          onChange={(e) => setEndpoint(e.target.value)}
        />
        <textarea
          value={code}
          onChange={(e) => setCode(e.target.value)}
        ></textarea>
        <div>{response}</div>
        <button onClick={handleSubmit}>Send</button>
      </main>
    </>
  );
};

export default Home;
